version: '3'

services:
  frontend:
    image: nginx:1.14-alpine
    volumes:
      - "./jdorg/build:/usr/share/nginx/html"
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - jdorg
  api:
    image: python:alpine3.7
    command: python /api/api.py
    volumes:
      - "./api:/api"
    ports:
      - "5000:5000"
    environment:
      - PROD=True
    networks:
      - jdorg
networks:
  jdorg:
    driver: bridge
