version: '3'

services:
  client:
    image: nginx:1.15.4-alpine
    volumes:
      - "./jdorg/build:/usr/share/nginx/html"
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
      - API_URL=http://localhost:5000
    networks:
      - jdorg
    depends_on:
      - api
  api:
    image: python:3.7-slim
    command:
      - /jdorg/api/start.sh
    volumes:
      - "./:/jdorg"
    ports:
      - "5000:80"
    environment:
      - PROD=True
    networks:
      - jdorg

networks:
  jdorg:
    driver: bridge
