version: '3'

services:
  client:
    image: nginx:1.15.4-alpine
    volumes:
      - "./jdorg/build:/usr/share/nginx/html"
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - jdorg

networks:
  jdorg:
    driver: bridge
