version: '3'
services:
  jdorg:
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - jdorg

networks:
  jdorg:
    driver: bridge
