{
 "title": "joshuaduffy.org",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "distributionId",
    "label": "DistributionId",
    "query": "dimension_values(us-east-1, AWS/CloudFront, Requests, DistributionId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests (for selected distribution)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Requests",
     "dimensions": { "DistributionId": "$distributionId", "Region": "Global" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Error Rate (for selected distribution)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "4XX Error Rate",
     "dimensions": { "DistributionId": "$distributionId", "Region": "Global" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "5XX Error Rate",
     "dimensions": { "DistributionId": "$distributionId", "Region": "Global" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Bytes Transferred (for selected distribution)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Bytes Downloaded",
     "dimensions": { "DistributionId": "$distributionId", "Region": "Global" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Bytes Uploaded",
     "dimensions": { "DistributionId": "$distributionId", "Region": "Global" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Estimated Bill",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Total",
     "dimensions": { "Currency": "USD" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "S3",
     "dimensions": { "Currency": "USD", "ServiceName": "AmazonS3" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "CloudFront",
     "dimensions": { "Currency": "USD", "ServiceName": "AmazonCloudFront" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "CloudWatch",
     "dimensions": { "Currency": "USD", "ServiceName": "AmazonCloudWatch" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Route53",
     "dimensions": { "Currency": "USD", "ServiceName": "AmazonRoute53" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "EC2",
     "dimensions": { "Currency": "USD", "ServiceName": "AmazonEC2" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "ECR",
     "dimensions": { "Currency": "USD", "ServiceName": "AmazonECR" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}