AWSTemplateFormatVersion: '2010-09-09'

Description: SSL/TLS Certificate

Resources:

  WebsiteWildcardCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join [".", ["*", !ImportValue DomainName]]
      ValidationMethod: DNS

Outputs:

  AcmCertificateArn:
    Description: ARN of the Certificate
    Value: !Ref WebsiteWildcardCertificate
    Export:
      Name: AcmCertificateArn
