AWSTemplateFormatVersion: '2010-09-09'

Description: Wildcard SSL/TLS certificate

Parameters:

  DomainName:
    Type: String
    Description: The DNS name of an Route 53 hosted zone e.g. joshuaduffy.org
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Must be a valid DNS zone name.

Resources:

  WebsiteWildcardCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join [".", ["*", !Ref DomainName]]
      ValidationMethod: DNS
