AWSTemplateFormatVersion: '2010-09-09'

Description: Route53 Record Sets for Google Mail

Parameters:

  FirstMx:
    Type: String
    Default: ASPMX.L.GOOGLE.COM

  SecondMx:
    Type: String
    Default: ALT1.ASPMX.L.GOOGLE.COM

  ThirdMx:
    Type: String
    Default: ALT2.ASPMX.L.GOOGLE.COM

  FourthMx:
    Type: String
    Default: ASPMX2.L.GOOGLE.COM

  FifthMx:
    Type: String
    Default: ASPMX3.L.GOOGLE.COM

  TTL:
    Type: Number
    Default: 3600

Resources:

  MxRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !ImportValue DomainName
      HostedZoneName: !Join
        - ""
        - [!ImportValue DomainName, "."]
      Type: MX
      TTL: !Ref TTL
      ResourceRecords:
        - !Sub "1 ${FirstMx}."
        - !Sub "5 ${SecondMx}."
        - !Sub "5 ${ThirdMx}."
        - !Sub "10 ${FourthMx}."
        - !Sub "10 ${FifthMx}."

  TxtRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !ImportValue DomainName
      HostedZoneName: !Join
        - ""
        - [!ImportValue DomainName, "."]
      Type: TXT
      TTL: !Ref TTL
      ResourceRecords:
        - !Join [" ", ["\"", "v=DKIM1;", "k=rsa;", "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCE3D4UpadZdsvTkj0hHHa7zGmI1gNUFQyxRlq2HHBvyReLb3vFdgOJY6D3rPjO7cNSQOGj5D/hnWvBGg4aztqVuDxwpIJR2A3h50R+IZZ7LyGtPNAGF5Sy8ldXbULRYs0LqHxWKFPm1f08lXaYhe51Io10mmMMy3jDuEXxNviFbQIDAQAB", "\""]]
        - !Join ["", ["\"", "google-site-verification=mtidxOHUnvq8iuTzqSxLJ0UNOxnWR2fXa5GJcfcSAjo", "\""]]
        - !Join ["", ["\"", "v=spf1 include:_spf.google.com ~all","\""]]
