version: '3'

services:
  grafana:
    image: grafana/grafana:5.3.4
    ports:
      - 3000:3000
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - ./credentials:/usr/share/grafana/.aws/credentials
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_VIEWERS_CAN_EDIT=false
    networks:
      - default

volumes:
  grafana_data: {}

networks:
  default:
    driver: bridge
